inventid/iaas

README.md, package.json, prepare.js, resize.js
@tiddolangerak or @joostverdoorn can you do a check of this?
@alexnederlof fyi
=> Ditch http in favour of express

package.json, resize.js
This finally fixes all remaining issues. Pfff
=> Finally fix all the things

resize.js
Closes #13 
Adds a very simple healthcheck to determine the status of the service
=> Add healthcheck

LICENSE, README.md
- Adds a default LICENSE
- Adds a badge to the Docker download count
@alexnederlof can you check whether the license I selected is applicable and OK for Magnet.me?
=> Badges + license

resize.js
@alexnederlof @wouter-willems Ready for review!
=> Allow to request the originals as well

provision.sh, resize.js
Required for magnetme which needs these sizes as well. Please check the diff with `?w=1` since i formatted everything
@alexwalterbos @alexnederlof @TiddoLangerak
=> Return the original sizes of the image on upload

resize.js
@TiddoLangerak I'm really sorry I didnt wait for your input on a former PR (https://github.com/inventid/live-image-resize/pull/21) since you did raise a number of valid points. I've addressed these in this PR!
=> Handle feedback as raised by an earlier PR

resize.js
@TiddoLangerak @alexnederlof @joostverdoorn please review
This PR addresses the issue where mobile clients do not actually rotate the image, but set it in the header info. We do need this though for consistency in the image viewing
Closes https://github.com/inventid/Neo/issues/1083
=> Auto orient images based on EXIF data

resize.js
@alexkolpa @alexwalterbos @inventid/tech Ready for review!
Closes https://github.com/inventid/live-image-resize/issues/27
=> Redirect to a sensible format in case a developer messes up

resize.js
Closes #30 
@michaeldejong @inventid/tech Ready for review!
I've extracted the cropping to a simple `if` stuff, which is then persisted to AWS
=> Fix the persistence of cropped photos on AWS

.jshintrc, Dockerfile, database.js, gulpfile.js, helpers.js, log.js, package.json, provision.sh, resize.js, shippable.yml, token.js, url-parsing.js
Closes #25 
- Prettify the code a bit
- Extract token logic
- Add CORS headers
- Made it a tad more ES6 compatible
Todo for later:
- Clean up the `image.*` mess
@michaeldejong @inventid/tech @TiddoLangerak @alexnederlof ready for review
Do not merge yet, I kinda want to test it as well!
=> Code cleanup and addition of cors headers

Dockerfile, README.md, dist/database.js, dist/gulpfile.js, dist/helpers.js, dist/log.js, dist/resize.js, dist/token.js, dist/url-parsing.js
Add the `dist` folder, README and updated the Dockerfile
=> Fixes to meta-development stuff

shippable.yml
=> Do not gulptest on shippable

.codeclimate.yml
Improve code climate reporting
=> New code climate tooling

.codeclimate.yml
Lets see whether this makes cc work again
=> Make code climate work?

.codeclimate.yml, .eslintrc, README.md
This should make eslint on cc work again and actually read the files :)
=> Make ESLint work

dist/helpers.js, dist/resize.js, helpers.js, package.json, resize.js
Closes #39 
@wouter-willems this caches :all_the_things:
I still have to test it thoroughly but will notify you when this is in the Docker containers
=> Added image caching

resize.js
@joostverdoorn Ready for review
=> Googlebot will always hit the root, triggering 502 log errors

.eslintrc, Log.js, Token.js, UrlParsing.js, database.js, helpers.js, index.js, shippable.yml
To ensure the code quality remains high.
We'll add some tests later
=> Let ESlint fiets over every branch

Dockerfile, Token.js, helpers.js, index.js, migrations/20160111165755.sql, migrations/20160111211907.sql, migrations/20160111214207.sql, migrations/README.md, package.json
Here we officially ditch sqlite, and welcome postgresql to the mix :)
1. Add a migration script for future use https://github.com/rogierslag/pg-migration
1. Switch to postgresql
@joostverdoorn @TiddoLangerak @wouter-willems Ready for review!
@alexnederlof for info
__To migrate current setups__
1. Export the sqlite data and schema
1. Import this in postgrsql
1. Create the pg-migration table https://github.com/rogierslag/pg-migration/blob/master/src/index.js#L24
1. Add the first changeset id in that table
1. Start the service
1. The remaining stuff will be migrated
=> Byebye sqlite, hello postgresql

config/default.json.example
Slightly more useful default example settings
=> Fix the default example settings

Dockerfile
refs https://github.com/inventid/live-image-resize/issues/52
=> Removed old SQLite from Dockerfile

Helpers.js, index.js
For non-image requests, the logging might trigger an error
=> Better handle logging on non-image requests

index.js
=> Make eslint happy

Dockerfile, README.md, Token.js, index.js
=> Remove SQLite reference from readme

README.md
Refs https://github.com/inventid/live-image-resize/issues/52
=> Add migration steps to the readme

Helpers.js
=> Fix 307 too large status code

README.md
@wouter-willems Can you check if this makes it clearer?
=> Explain the development steps better

.eslintrc, Token.js, index.js
=> don't neglect the provided ratio when max size is reached

package.json
This updates all dependencies to their latest versions (matching semver)
@inventid/tech ready for review (mostly whether you know any known problems with these?)
=> Updated all packages to latest versions

README.md
I forgot this, but it should be in the readme
=> Explain canvas in README

.eslintrc, package.json, shippable.yml, src/aws.js, src/dbCache.js, src/image.js, src/imageResponse.js, src/index.js, src/log.js, src/token.js, src/urlParameters.js
Bunch of fixes related to ESlint.
Also fixes a bug where a tempfile could not be deleted after autoOrienting it
=> Fixes for ESLint

src/imageResponse.js, src/index.js
So the logging is slightly more consistent
=> Make logging more consistent

src/image.js
I'm slightly retarded and completely missed this
@wouter-willems
=> Fix incorrect repaging when cropping

README.md, src/aws.js, src/dbCache.js
Closes https://github.com/inventid/iaas/issues/78
=> Rendered at to aws

Dockerfile
This should improve concurrent throughput
=> Increase the concurrent workers

Dockerfile
Refs https://github.com/inventid/iaas/pull/86#issuecomment-266993614
=> Set a proper instance count, which can then be configured using Docker assignments

src/image.js, src/imageResponse.js
Based on https://github.com/aheckmann/gm/commit/ccc128c5f57eca9f53c5c4d8c28a8ecb703ed431
- Adds a bufferStream command
- Log the content of stderr if available
=> Even more logging

src/dbCache.js
=> Do not count a image race to the db as a problem

src/imageResponse.js
=> Register stream errors before catching exceptions

src/imageResponse.js, src/index.js
1. Move some additional logging statements to `debug`
1. Switch the streams to buffers (like we do for AWS which works fine)
=> Switch to buffers instead of streams

.gitignore, npm-shrinkwrap.json, package.json, src/image.js, src/token.js
Updates some dependencies to their newest versions
=> Dependency update

README.md, config/default.json.example, src/aws.js, src/image.js, src/imageResponse.js
Some changes to make cloudfront support as asset cache easier
=> Cloudfront support

src/index.js
In case a db server goes down, shutdown and try to reconnect.
=> Allow db connection recovery

src/dbCache.js, src/image.js, src/index.js
In SQL, `null != null`. So all auto-quality images would miss the cache
always. We need to use `IS NOT DISTINCT FROM` to compare with null.
=> Fix postgres `= null` check

src/imageResponse.js
So the quality status can actually be tracked
=> Fix the description in the name

src/helper.js, src/index.js
- Report the uptime in seconds
- Properly round the generationCount as well
- Log the number of uploads as well
=> Improved stats

src/image.js
1. We now apply the timeout in the subClass as well (docs and code are a bit strange on where it should go, so now I've just opted for both)
1. Also apply the timeout when determining sizes
@AlexKolpa @alexnederlof RFR
=> Apply the timeouts consistently

Dockerfile, npm-shrinkwrap.json, package.json, shippable.yml, src/aws.js, src/databases/index.js, src/databases/postgresql.js, src/dbCache.js, src/imageResponse.js, src/index.js, src/metrics/index.js, src/token.js
For postgresql, introduce database pooling
Closes https://github.com/inventid/iaas/issues/47
=> Make the database layer pluggable

Dockerfile, src/image.js
Refs https://github.com/inventid/iaas/issues/115
__Still needs to be tested__
=> Strip image data

src/databases/postgresql.js
this should prevent log spamming when a client is misbehaving
@AlexKolpa @joostverdoorn RFR
=> In case the same image is requested multiple times, handle the error properly

src/metrics/influx.js
Writes towards an influx instance were not properly batched, causing  potential overload on influx itself
@AlexKolpa RFR
=> Batch influx writes

src/aws.js, src/imageResponse.js, src/index.js, src/metrics/influx.js, src/robotsTxt.js
This syncs the current value of the robots.txt to the remove endpoint 
@joostverdoorn @AlexKolpa Can you check the code?
=> Proper robots.txt handling on remote host

shippable.yml
Update the test suite to test with the correct versions of node.
=> Update test suite
