- config/default.json.example
- prepare.js
- resize.js
From a standpoint of deployment, it makes sense to allow an operator to specify where the database should be located (just as was already happening for the `originals_dir`). This PR fixes that
@inventid/tech @inventid/magnet-collaboration please review!
> Make the location of the db-file configurable

- package.json
- resize.js
In case you have a reverse-proxy in front of the app, it would not send proper headers, so ytou would not received a 404 error. This commit makes a 404 more explicit, and allow the proxy to forward it appropriately
> Send explicit 404 header if file does not exist

- package.json
- resize.js
Closes #5 
Make much more verbose logging
```
Using db file: /tmp/db.cache
Server started listening
{"datetime":1433709090509,"severity":"info","message":"Requesting file test in png format in a 400x402px resolution"}
{"datetime":1433709090514,"severity":"info","message":"cache hit for test.png(400x402px)"}
{"datetime":1433709090515,"method":"GET","url":"/test_200_201_2x.png","client":"10.0.2.2","response_time":0.006659376,"response_status":307,"cache_hit":true,"fileName":"test","resolutionX":400,"resolutionY":402,"fileType":"png"}
{"datetime":1433709096751,"severity":"info","message":"Requesting file test in png format in a 1000x1005px resolution"}
{"datetime":1433709096754,"method":"GET","url":"/test_200_201_5x.png","client":"10.0.2.2","response_time":0.002655131,"response_status":200,"c …
```
> Log requests and response times

- Dockerfile
This improves the dockerfile by moving stuff around.
By adding the dependencies before the application, we do not need to run npm install every time when dockerizing the app, since `package.json` has not been updated then. To be honest, we probably only need to run the last three commands now, since the remainder can be cached perfectly
@alexnederlof ready for review!
> Improve dockerfile to leverage container caching

- config/default.json.example
- resize.js
@joostverdoorn @alexnederlof @TiddoLangerak Ready for review
For inventid, we do not want indexing of these images, so we set the variable `allow_indexing` to `false` (the default). Meanwhile Magnetme might want to allow indexing for this, so they can override the value in the configuration json.
This also prevents crawlers from hitting 404s, or longer waiting times.
> Use robots.txt for crawler handling

- config/default.json.example
- resize.js
This limits the sizes of images to a maximum width and height to ensure nobody can simply ddos the service by requesting insanely large pictures
@inventid/tech @alexnederlof @TiddoLangerak @michaeldejong @alexwalterbos
> Introduce limits on the requested image dimensions

- dist/resize.js
- resize.js
`HEAD` request won't automatically get redirected by browsers. It is therefore more useful to resolve the redirect already internally, such that clients can detect if the image can be found without having to perform an explicit extra request. This is also needed for some libraries to work correctly (e.g. the [angular-retina](https://github.com/jrief/angular-retina) library we use at Magnet.me).
@rogierslag @joostverdoorn @wouter-willems - RFR!
> Removed redirect on HEAD request

- dist/resize.js
- resize.js
It's the difference between this:
And this (stopped recording early, but you get the point :wink:):
@rogierslag @joostverdoorn @wouter-willems @alexnederlof - RFR
> Enabled interlacing for jpegs

- UrlParsing.js
- index.js
- shippable.yml
This is the same as fitting the image, but additionally it fills the bordesr until the exact desired height and width
@wouter-willems for review
After merging we can switch to the `beta` branch for testing
> Allow for canvas parsing

- Helpers.js
- index.js
- package.json
As requested by @wouter-willems, setting the query parameters `x`, `y`, `width` and `height` allow to crop the picture when uploading. This prevents cropping weirdness in the browser if we handle it using javascript
Ready for review @TiddoLangerak @joostverdoorn @wouter-willems
> Allow optional cropping of images while uploading

- create-release.sh
- migrations/20160705120249.sql
- package.json
- src/dbCache.js
- src/index.js
This will include the render time in the `images` table. That way it will allow us to purge any caches which were rendered incorrectly due to a bug.
Flyby: Additionally fix an async/await which missed the await
@wouter-willems ready for review!
> Log the render time

- src/image.js
- src/index.js
Because `Number(0) || undefined` yields the latter 
@wouter-willems
> Fix crop on upload for an edge case

- src/helper.js
- src/imageResponse.js
Slightly sad moment :\
Additionally I reduced the cache time a bit, since it allows us to prune caches easier
@TiddoLangerak @wouter-willems @joostverdoorn ready for review
> Cache redirect less aggressively

- src/image.js
It seems that interlacing gets lost with certain operations, such as
cropping. Moving interlacing to the end makes sure the final image is
interlaced.
For #80
Note: I haven't tested this with `iaas` itself yet, since I don't have the entire postgres installation setup (and no time to do it now), but I have verified this behaviour with CLI imagemagick. @rogierslag do we already have a ready made docker instance to test this with, or do I still need to setup postgres & configs myself?
> Move interlacing to the end

- Dockerfile
- README.md
- config/default.json.example
- npm-shrinkwrap.json
- src/imageResponse.js
Permanent redirects can result in a significant speed up, since they
don't require to be re-fetched. With a permanent redirect images can
thus be served directly from cache. On pages with many images - where
concurrent requests are throttled - this can result in a significant
speed up.
The use of the permanent redirect is configurable: if a non-zero
redirect timeout is set then a permanent redirect is used, otherwise it
still uses a temporary one. This therefore doesn't change anything for
existing configurations, it needs to be explicitly enabled.
@rogierslag - I wanted to test this, but I don't have any AWS keys available. Do we have some for testing purposes?
> Allow permanent redirects to be used

- Dockerfile
- npm-shrinkwrap.json
- package.json
- shippable.yml
- src/aws.js
- src/image.js
@TiddoLangerak I shrinkwrapped incorrectly, using our internal registry as a dependency (failing all CI builds)
However if I try to build with the latest versions, babel errors with 
```
Error: aws.js: You gave us a visitor for the node type "ForAwaitStatement" but it's not a valid type
at verify (/usr/local/lib/node_modules/babel-cli/node_modules/babel-traverse/lib/visitors.js:224:13)
at Object.explode (/usr/local/lib/node_modules/babel-cli/node_modules/babel-traverse/lib/visitors.js:90:3)
at traverse (/usr/local/lib/node_modules/babel-cli/node_modules/babel-traverse/lib/index.js:81:12)
at NodePath.traverse (/usr/local/lib/node_modules/babel-cli/node_modules/babel-traverse/lib/path/index.js:147:25)
at exports.default (/opt/iaas/node_modules/babel-preset-stage-3/node_modules/babel-helper-r …
```
> Try to fix the docker build

- src/imageResponse.js
It seems that the iaas processes loses some convert processes. While running for slightly over 12 hour, we have 84 of these processes open.
Logging indicates that for these images the AWS images were created successfully, but the live images do not report success. I suspect this is because the client has moved to another page before the image was resized, and therefore the pipe into the response fails (since the client has disconnected). Additionally since the stream is not closed on an error, this process remains open.
In order to investigate, I want to log any errors in that part of the sending. In case the stream did error, we close both the response and the stream.
There are two possible outcomes for this fix:
1. We do no longer see an ever increasing amount of convert processes. …
> Additional error logging on losing processes

- src/dbCache.js
- src/imageResponse.js
- src/index.js
This should effectively handle browsers which "give up" on a resource before its completed. The stream is properly terminated, so the convert process is cleaned up
@TiddoLangerak
> Handle browser disconnection while live live conversion is running

- src/image.js
The filling of a transparent background for JPG requests should only happen after the fitting has taken place, otherwise the fitting can be done incorrectly
> Only flatten the image after it has been cropped

- README.md
- config/default.json.example
- src/image.js
Sometimes gm can hang, bringing down the machine it is hosted on. By adding a timeout to the image actions, we will kill the process and return an error to the requester
> Allow image actions to time out after a while

- README.md
- migrations/20170704100751.sql
- src/aws.js
- src/dbCache.js
- src/image.js
- src/imageResponse.js
- src/index.js
- src/urlParameters.js
This adds support for an optional `?quality` parameter that allows
compressing jpegs. I experimented with a small set of images and found
that with `?quality=60` you reduce the filesize by more than half with
barely any noticeable difference.
This change also comes with another small fly-by: previously when no
explicit dimensions where given then the original file would be
returned, regardless of query parameters (e.g. blur wouldn't be taken
into account). Now, the dimensionless url will detect the blur and
quality filters and redirect to the maximum supported size image with
the filters applied.
@rogierslag can you review and perhaps also test it out locally to double check I didn't make mistakes?
> Add support for JPG compression

- migrations/20170704100751.sql
- src/dbCache.js
- src/image.js
- src/urlParameters.js
if a column for postgresql is NULL the unique index does not hold.
Hence multiple things could be included, and due to the fact that we
checked on exactly one result, we would always fall through.
So I moved everything back to integers which is more suitable anyhow
```
imageresizer=# \d images;
Table "public.images"
Column    |           Type           |           Modifiers            
-------------+--------------------------+--------------------------------
id          | character varying(255)   | 
x           | integer                  | 
y           | integer                  | 
fit         | character varying(8)     | 
file_type   | character varying(16)    | 
url         | character varying(255)   | 
blur        | boolean                  | default false
rendered_at | timestamp with …
```
> Fix quality determination

- src/imageResponse.js
- src/index.js
- src/integerCounter.js
- src/log.js
- src/urlParameters.js
When enabled, this PR ensures that every 5 minutes each [PM2](http://npmjs.org/pm2) instance will report the following data:
1. Number of cache hits
1. Number of cache misses which triggered generations
1. Average number of generations per minute
1. Cache hit ratio
Note that if there is a reverse proxy before the iaas, many cache hits will be served by that service. The `generationsPerMinute` flag can be used to determine how heavily the resizing is hit.
> Log stats for hits and miss ratios

- src/imageResponse.js
Closes https://github.com/inventid/iaas/issues/7
After moving everything to buffers, we can reuse the buffer for the live image and AWS
This cuts the number of conversions in half so that is a nice free improvement
@AlexKolpa @alexnederlof
> Reuse the buffer

- src/databases/postgresql.js
- src/imageResponse.js
- src/index.js
- src/metrics/console.js
- src/metrics/index.js
- src/metrics/influx.js
This should ensure that we can keep track of metrics of failing conversions
Flyby: 
- Prevent early instantiation of metrics
- Ensure the system would be properly restarted after a DB crash
> Timeout metrics

- src/token.js
In case a token was already created, `token.js` expected an error to be thrown by `database.createToken`, however that function already handles the exception internally, returning an undefined value to indicate no new token has been created. Because of this `token.js` thought the new token was persisted correctly and returned the unpersisted token. Instead it now return the value as provided by `database.createToken`, so `/token` can indicate a proper 403 here.
> Properly handle token creation for duplicate tokens

- src/image.js
🤦‍♂️ Forgot to set this properly, and obviously I ran my tests locally with quality is 100 but in production I compared a quality 100 to quality of JPG (which was set to a lower value)
> Properly set qualities for webp as well

- Dockerfile
- src/databases/postgresql.js
- src/index.js
When a database failed, upon the first retry the migration would fail, but by not correctly passing the error the system would enter a frozen state. Not serving requests, but not retrying either. By passing the error properly to the callback, this is fixed.
Additionally when running Docker, this adds a retry policy so it keeps retrying with an exponential backoff in order to resume service as soon as possible.
Easiest reviewing with the [`?w=1`](https://github.com/inventid/iaas/pull/127/files?w=1) option
@AlexKolpa @joostverdoorn Ready for review
> Improve restart resiliency

- src/databases/postgresql.js
- src/index.js
- src/token.js
Just as with requesting images, during image uploads clients may also lose connectivity for whatever reason. This could cause a race condition where a `image_id` would remain reserved indefinitely. Very annoying for clients who eg depend on the original images hash to determine its `image_id`.
This fixes that by clearing non-completed tokens for those requests from the database.
It is quite a indent change, so take a look at the [`?w=1`](https://github.com/inventid/iaas/pull/130/files) variant
> Handle terminated connections on image uploads

- Dockerfile
- README.md
- src/databases/postgresql.js
- src/index.js
- src/metrics/index.js
We noticed that sometimes database pools got exhausted, leading to really slow generations and uploads. I cannot figure out where exactly, but it seems something in the database is slow, leading to some resource starvation. When we upped the pool size, timings dropped significantly (see images below)
1. This PR adds instrumentation to all database calls
1. It reduces the frequency of checking whether a dababase is alive
1. It adds `dumb-init` so the Docker container closes better
1. Adds missing documentation in the README
**redirect timings**
**number of database requests waiting for connections**
'm curious to see whether something is off in the database, or whether some calls are just performing badly
> Log database calls timings
